// NCS Authentic Vocabulary by Unit
// Progressive vocabulary following NCS curriculum

export const ncsVocabularyByUnit = {
  1: {
    progressive: ["aid", "babes", "baits", "bat", "bays", "bet", "bit", "but", "cab", "cap", "chat", "chip", "cop", "cot", "cut", "date", "do", "each", "is", "jab", "job", "page", "pat", "pay", "pays", "pep", "pet", "pit", "pot", "put", "tab", "tap", "the", "tip", "to", "top", "which"],
    unitSpecific: ["pay", "pays", "page", "pep", "bays", "babes", "aid", "baits", "date", "which", "is", "the", "do", "to", "pat", "bat", "tap", "tab", "cap", "cab"],
    theoryPoints: ["Light downward stroke for P (Pay)", "Heavy downward stroke for B (Bee)", "Light upward stroke for T (Tee)", "Heavy upward stroke for D (Dee)", "Light slanted stroke for CH (Chay)", "Heavy slanted stroke for J (Jay)", "Second-place dot vowels positioned to the right"]
  },
  2: {
    progressive: ["aid", "as", "babes", "baits", "bat", "bays", "bet", "bit", "but", "cab", "cap", "cash", "chat", "chip", "coffee", "cop", "cot", "cut", "date", "dish", "do", "each", "face", "file", "fish", "five", "give", "has", "hash", "have", "his", "house", "if", "is", "jab", "job", "nice", "of", "office", "page", "pat", "pay", "pays", "pep", "pet", "pit", "place", "pot", "put", "safe", "save", "say", "see", "she", "shop", "staff", "tab", "tap", "that", "the", "these", "think", "this", "tip", "to", "top", "voice", "was", "which", "wish", "with"],
    unitSpecific: ["if", "of", "safe", "staff", "file", "five", "have", "give", "voice", "save", "this", "that", "the", "these", "think", "with", "say", "see", "his", "has"],
    theoryPoints: ["Light curved stroke for F (Ef)", "Heavy curved stroke for V (Vee)", "Light TH stroke for voiceless TH (ith)", "Heavy TH stroke for voiced TH (thee)", "Curved S and Z strokes", "SH and ZH formations", "Second-place dash vowels for long sounds"]
  },
  3: {
    progressive: ["aid", "all", "as", "babes", "baits", "bat", "bays", "bet", "bit", "but", "cab", "call", "can", "cap", "cash", "chat", "chip", "coffee", "come", "coming", "cop", "cot", "cut", "date", "day", "dish", "do", "each", "face", "file", "fish", "five", "game", "give", "go", "going", "good", "has", "hash", "have", "his", "home", "house", "if", "is", "jab", "job", "key", "king", "line", "long", "looking", "make", "man", "may", "me", "my", "name", "nice", "nine", "of", "office", "page", "pat", "pay", "pays", "pep", "pet", "pit", "place", "pot", "put", "ring", "safe", "save", "say", "see", "she", "shop", "some", "song", "staff", "tab", "tap", "that", "the", "these", "thing", "think", "this", "time", "tip", "to", "top", "voice", "was", "way", "well", "which", "will", "wish", "with", "working", "wrong", "yes", "yet", "you", "young"],
    unitSpecific: ["key", "go", "good", "game", "make", "name", "man", "can", "my", "me", "home", "come", "some", "time", "nine", "line", "long", "wrong", "song", "ring"],
    theoryPoints: ["Horizontal strokes written left to right", "K and G horizontal stroke formation", "M and N horizontal strokes", "NG horizontal stroke", "Upward L stroke formation", "W and Y upward stroke principles"]
  },
  4: {
    progressive: ["agree", "aid", "all", "as", "babes", "baits", "bat", "bays", "be", "bet", "bit", "but", "cab", "call", "came", "can", "cap", "cash", "chat", "chip", "coffee", "come", "coming", "cop", "cot", "cut", "date", "day", "dish", "do", "each", "face", "fee", "file", "fish", "five", "free", "game", "give", "go", "going", "good", "has", "hash", "have", "he", "his", "home", "house", "if", "is", "jab", "job", "key", "king", "lay", "lee", "line", "long", "looking", "make", "man", "may", "me", "my", "name", "nice", "nine", "of", "office", "page", "pat", "pay", "pays", "pea", "pep", "pet", "pit", "place", "play", "pot", "put", "ring", "safe", "same", "save", "say", "sea", "see", "she", "shop", "some", "song", "staff", "stay", "tab", "take", "tap", "tea", "that", "the", "these", "thing", "think", "this", "three", "time", "tip", "to", "top", "tree", "voice", "was", "way", "we", "well", "which", "will", "wish", "with", "working", "wrong", "yes", "yet", "you", "young"],
    unitSpecific: ["take", "make", "came", "same", "name", "game", "place", "face", "way", "day", "may", "say", "stay", "play", "lay", "pay", "see", "be", "we", "he"],
    theoryPoints: ["First-place vowels written above horizontal strokes", "First-place vowels to the left of other strokes", "Position writing principles", "Dot and dash vowel formation in first place"]
  },
  5: {
    progressive: ["agree", "aid", "all", "as", "babes", "baits", "bat", "bays", "be", "bet", "bit", "book", "bow", "but", "cab", "call", "came", "can", "cap", "cash", "chat", "chip", "coffee", "come", "coming", "cook", "cop", "cot", "cow", "crop", "cup", "cut", "date", "day", "dish", "do", "drop", "each", "face", "fee", "file", "fish", "five", "food", "free", "game", "give", "go", "going", "good", "gut", "has", "hash", "have", "he", "his", "home", "house", "how", "hut", "if", "is", "jab", "job", "key", "king", "know", "lay", "lee", "line", "long", "look", "looking", "low", "make", "man", "may", "me", "mood", "my", "name", "nice", "nine", "no", "now", "nut", "of", "office", "page", "pat", "pay", "pays", "pea", "pep", "pet", "pit", "place", "play", "pot", "put", "ring", "rut", "safe", "same", "save", "say", "sea", "see", "she", "shop", "show", "shut", "so", "some", "song", "staff", "stay", "stop", "tab", "take", "tap", "tea", "that", "the", "these", "thing", "think", "this", "three", "throw", "time", "tip", "to", "too", "took", "top", "tree", "two", "up", "voice", "was", "way", "we", "well", "which", "who", "will", "wish", "with", "wood", "working", "wrong", "yes", "yet", "you", "young"],
    unitSpecific: ["go", "so", "no", "do", "to", "who", "too", "two", "you", "how", "now", "cow", "bow", "low", "show", "know", "throw", "book", "look", "took"],
    theoryPoints: ["Third-place vowels below horizontal strokes", "Third-place vowels to the right of other strokes", "Heavy dot and dash formation for O, U, OO sounds", "Position writing with third-place vowels"]
  },
  6: {
    progressive: ["agree", "aid", "all", "as", "babes", "baits", "bat", "bays", "be", "beast", "best", "bet", "bit", "blast", "book", "bow", "but", "cab", "call", "came", "can", "cap", "cash", "cast", "chat", "chest", "chip", "coffee", "come", "coming", "cook", "cop", "cost", "cot", "cow", "crop", "cup", "cut", "date", "day", "dish", "do", "drop", "each", "east", "face", "fast", "feast", "fee", "file", "first", "fish", "five", "food", "free", "game", "give", "go", "going", "good", "guest", "gut", "has", "hash", "have", "he", "his", "home", "house", "how", "hut", "if", "is", "jab", "job", "just", "key", "king", "know", "last", "late", "lay", "least", "lee", "left", "legal", "let", "level", "life", "light", "likely", "line", "list", "live", "local", "long", "look", "looking", "lot", "love", "lovely", "low", "loyal", "make", "man", "may", "me", "mood", "must", "my", "name", "nest", "nice", "nine", "no", "now", "nut", "of", "office", "page", "past", "pat", "pay", "pays", "pea", "pep", "pet", "pit", "place", "play", "post", "pot", "put", "rest", "ring", "rut", "safe", "same", "save", "say", "sea", "see", "she", "shop", "show", "shut", "so", "some", "song", "staff", "stay", "stop", "tab", "take", "tap", "tea", "test", "that", "the", "these", "thing", "think", "this", "three", "throw", "time", "tip", "to", "too", "took", "top", "tree", "trust", "two", "up", "voice", "was", "way", "we", "well", "west", "which", "who", "will", "wish", "with", "wood", "working", "wrong", "yes", "yet", "you", "young"],
    unitSpecific: ["so", "see", "say", "some", "same", "safe", "staff", "last", "best", "rest", "test", "fast", "past", "cast", "list", "cost", "must", "just", "first", "trust"],
    theoryPoints: ["S Circle formation and attachment rules", "S Circle joins to straight and curved strokes", "Downward L stroke formation", "L stroke positioning and vowel relationships"]
  },
  7: {
    progressive: ["agree", "aid", "all", "are", "as", "babes", "baits", "bat", "bays", "be", "bear", "beast", "best", "bet", "bit", "blast", "book", "bow", "but", "cab", "call", "came", "can", "cap", "care", "cash", "cast", "chat", "chest", "chip", "clear", "coffee", "come", "coming", "compare", "cook", "cop", "cost", "cot", "cow", "crop", "cup", "cut", "date", "day", "dear", "declare", "dish", "do", "drop", "each", "east", "every", "face", "fast", "fear", "feast", "fee", "file", "first", "fish", "five", "food", "for", "free", "game", "give", "go", "going", "good", "guest", "gut", "has", "hash", "have", "he", "hear", "here", "his", "home", "house", "how", "hut", "if", "is", "jab", "job", "just", "key", "king", "know", "last", "late", "lay", "least", "lee", "left", "legal", "let", "level", "life", "light", "likely", "line", "list", "live", "local", "long", "look", "looking", "lot", "love", "lovely", "low", "loyal", "make", "man", "may", "me", "mood", "more", "must", "my", "name", "near", "nest", "nice", "nine", "no", "now", "nut", "of", "office", "or", "our", "page", "past", "pat", "pay", "pays", "pea", "pep", "pet", "pit", "place", "play", "post", "pot", "prepare", "put", "rare", "repair", "rest", "ring", "rut", "safe", "same", "save", "say", "sea", "see", "share", "she", "shop", "show", "shut", "so", "some", "song", "sorry", "spare", "square", "staff", "stay", "stop", "tab", "take", "tap", "tea", "test", "that", "the", "their", "there", "these", "thing", "think", "this", "three", "throw", "time", "tip", "to", "too", "took", "top", "tree", "trust", "two", "up", "very", "voice", "was", "way", "we", "wear", "well", "were", "west", "where", "which", "who", "will", "wish", "with", "wood", "working", "wrong", "year", "yes", "yet", "you", "young"],
    unitSpecific: ["are", "our", "or", "for", "more", "were", "their", "there", "where", "here", "near", "dear", "clear", "year", "hear", "fear", "wear", "bear", "care", "share"],
    theoryPoints: ["R stroke formation principles", "R stroke joining rules", "R in initial, medial, and final positions", "R stroke with vowel combinations"]
  },
  8: {
    progressive: ["about", "agree", "aid", "all", "are", "as", "babes", "baits", "bat", "bays", "be", "bear", "beast", "best", "bet", "bit", "blast", "book", "bow", "bright", "brown", "but", "buy", "by", "cab", "call", "came", "can", "cap", "care", "cash", "cast", "chat", "chest", "chip", "clear", "coffee", "come", "coming", "compare", "cook", "cop", "cost", "cot", "cow", "crop", "crown", "cry", "cup", "cut", "date", "day", "dear", "declare", "dish", "do", "down", "drop", "dry", "each", "east", "every", "eye", "face", "fast", "fear", "feast", "fee", "fight", "file", "fine", "first", "fish", "five", "fly", "food", "for", "found", "free", "game", "give", "go", "going", "good", "ground", "guest", "gut", "guy", "has", "hash", "have", "he", "hear", "here", "high", "his", "home", "house", "how", "hut", "if", "is", "jab", "job", "just", "key", "king", "know", "last", "late", "lay", "least", "lee", "left", "legal", "let", "level", "life", "light", "likely", "line", "list", "live", "local", "long", "look", "looking", "lot", "love", "lovely", "low", "loyal", "make", "man", "may", "me", "might", "mine", "mood", "more", "must", "my", "name", "near", "nest", "nice", "night", "nine", "no", "now", "nut", "of", "office", "or", "our", "page", "past", "pat", "pay", "pays", "pea", "pep", "pet", "pit", "place", "play", "post", "pot", "prepare", "put", "quite", "rare", "repair", "rest", "right", "ring", "round", "rut", "safe", "same", "save", "say", "sea", "see", "share", "she", "shop", "show", "shut", "sight", "sky", "so", "some", "song", "sorry", "sound", "spare", "square", "staff", "stay", "stop", "tab", "take", "tap", "tea", "test", "that", "the", "their", "there", "these", "thing", "think", "this", "three", "throw", "time", "tip", "to", "too", "took", "top", "town", "tree", "trust", "try", "two", "up", "very", "voice", "was", "way", "we", "wear", "well", "were", "west", "where", "which", "white", "who", "why", "will", "wine", "wish", "with", "wood", "working", "write", "wrong", "year", "yes", "yet", "you", "young"],
    unitSpecific: ["eye", "my", "by", "try", "fly", "cry", "dry", "sky", "why", "buy", "guy", "high", "right", "night", "light", "might", "sight", "fight", "bright", "quite"],
    theoryPoints: ["Diphthong representation methods", "First-place and third-place diphthongs", "Triphone formation rules", "Diphone usage principles"]
  },
  9: {
    progressive: ["about", "agree", "aid", "all", "are", "as", "babes", "baits", "bat", "bays", "be", "bear", "beast", "behind", "best", "bet", "bit", "blast", "book", "bow", "bright", "brown", "but", "buy", "by", "cab", "call", "came", "can", "cap", "care", "cash", "cast", "chat", "chest", "chip", "clear", "coffee", "come", "coming", "compare", "cook", "cop", "cost", "cot", "cow", "crop", "crown", "cry", "cup", "cut", "date", "day", "dear", "declare", "dish", "do", "down", "drop", "dry", "each", "east", "every", "eye", "face", "fast", "fear", "feast", "fee", "fight", "file", "fine", "first", "fish", "five", "fly", "food", "for", "found", "free", "game", "give", "go", "going", "good", "ground", "guest", "gut", "guy", "had", "hand", "happy", "hard", "has", "hash", "have", "he", "head", "health", "hear", "heavy", "help", "her", "here", "high", "him", "his", "hold", "home", "hope", "hour", "house", "how", "hut", "if", "is", "jab", "job", "just", "key", "king", "know", "last", "late", "lay", "least", "lee", "left", "legal", "let", "level", "life", "light", "likely", "line", "list", "live", "local", "long", "look", "looking", "lot", "love", "lovely", "low", "loyal", "make", "man", "may", "me", "might", "mine", "mood", "more", "must", "my", "name", "near", "nest", "nice", "night", "nine", "no", "now", "nut", "of", "office", "or", "our", "page", "past", "pat", "pay", "pays", "pea", "pep", "perhaps", "pet", "pit", "place", "play", "post", "pot", "prepare", "put", "quite", "rare", "repair", "rest", "right", "ring", "round", "rut", "safe", "same", "save", "say", "sea", "see", "share", "she", "shop", "show", "shut", "sight", "sky", "so", "some", "song", "sorry", "sound", "spare", "square", "staff", "stay", "stop", "tab", "take", "tap", "tea", "test", "thank", "that", "the", "their", "there", "these", "thing", "think", "this", "those", "three", "through", "throw", "time", "tip", "to", "too", "took", "top", "town", "tree", "trust", "try", "two", "up", "very", "voice", "was", "way", "we", "wear", "well", "were", "west", "what", "when", "where", "which", "white", "who", "why", "will", "wine", "wish", "with", "wood", "working", "write", "wrong", "year", "yes", "yet", "you", "young"],
    unitSpecific: ["he", "his", "him", "her", "has", "had", "have", "how", "who", "what", "when", "where", "which", "why", "help", "head", "hand", "hard", "hear", "here"],
    theoryPoints: ["H consonant formation", "H in initial position", "H combinations and blends", "Silent H recognition"]
  },
}
